[package]
name = "knot-core"
version = "1.24.1"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
arc-swap.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
directories.workspace = true
uuid.workspace = true
rust-i18n.workspace = true
plist.workspace = true

[dev-dependencies]
tempfile.workspace = true
